# conda-environment.yml
name: base
channels:
  - defaults
dependencies:
  - python=3.10  # Stick to one Python version (3.10 recommended)
  - numpy
  - pandas
  - flake8       # For linting
  - pytest       # For testing
  # Add other dependencies here
