name: Lint with pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Match your project's version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pylint  # Explicitly install pylint
          pip install -e .    # Install your package (requires setup.py)
      - name: Run pylint
        run: pylint missing_words_game.py
    
